apiVersion: v1
kind: Secret
metadata:
  name: micro-store-secrets
  namespace: micro-store
type: Opaque
stringData:
  JWT_SECRET: "supersecretjwtkey"
  STRIPE_SECRET_KEY: "sk_test_..."
  
  # Postgres Container Service
  POSTGRES_USER: "adminuser"
  POSTGRES_PASSWORD: "P@ssw0rd123!"
  POSTGRES_HOST: "postgres"
  POSTGRES_DB: "shopping_site"
  
  # Mongo Atlas
  MONGO_URI: "REPLACE_WITH_MONGO_URI"
  
  # Azure Redis
  REDIS_URL: "REPLACE_WITH_REDIS_URL"
  
  # Azure Storage
  AZURE_STORAGE_ACCOUNT_KEY: "REPLACE_WITH_AZURE_STORAGE_KEY"
  
  # Google OAuth
  GOOGLE_CLIENT_ID: "REPLACE_WITH_GOOGLE_CLIENT_ID"
  
  # SMTP
  SMTP_USER: "REPLACE_WITH_SMTP_USER"
  SMTP_PASS: "REPLACE_WITH_SMTP_PASS"
  RECEIVER_EMAIL: "REPLACE_WITH_RECEIVER_EMAIL"
