# Default values for micro-store.

common:
  replicaCount: 1
  imagePullPolicy: Always
  serviceType: ClusterIP

global:
  imageRegistry: "microstoreacr2026.azurecr.io"
  imagePullSecret: ""
  environment: "production"
  domain: "48.216.152.209.nip.io"

ingress:
  enabled: true
  className: "nginx"
  # The IP will be assigned to the Ingress Controller LoadBalancer
  # We will use nip.io to create hostnames like:
  # staging-micro-store.IP.nip.io
  # prod-micro-store.IP.nip.io
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

services:
  frontend:
    enabled: true
    useRegistry: true
    image: "manushau/frontend"
    tag: "latest"
    containerPort: 3000
    servicePort: 3000
    healthCheck: "/"
    env:
      # This will be overridden by the Ingress hostname
      NEXT_PUBLIC_API_BASE_URL: "http://48.216.152.209.nip.io"
      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: "pk_test_51TPFxMK7EULgYmVsENzQ7YZxRIgKoQU36REWM4KouIkJypxtH23f1P3fq1ygduQRDuWjcFIHJMr9J5JOdiT1WLmN00cMFjyCpM"
      
  api-gateway:
    enabled: true
    useRegistry: true
    image: "manushau/api-gateway"
    tag: "latest"
    containerPort: 8080
    servicePort: 8080
    healthCheck: "/gateway/health"

  auth-service:
    enabled: true
    useRegistry: true
    image: "manushau/auth-service"
    tag: "latest"
    containerPort: 3001
    serviceType: ClusterIP
    servicePort: 3001
    env:
      PORT: "3001"
      POSTGRES_PORT: "5432"

  catalog-service:
    enabled: true
    useRegistry: true
    image: "manushau/catalog-service"
    tag: "latest"
    containerPort: 3002
    serviceType: ClusterIP
    servicePort: 3002
    env:
      PORT: "3002"
      POSTGRES_PORT: "5432"
      AZURE_CONTAINER_NAME: "product-images"

  cart-service:
    enabled: true
    useRegistry: true
    image: "manushau/cart-service"
    tag: "latest"
    containerPort: 3003
    serviceType: ClusterIP
    servicePort: 3003
    env:
      PORT: "3003"

  checkout-service:
    enabled: true
    useRegistry: true
    image: "manushau/checkout-service"
    tag: "latest"
    containerPort: 3004
    serviceType: ClusterIP
    servicePort: 3004
    env:
      PORT: "3004"
      POSTGRES_PORT: "5432"

  email-service:
    enabled: true
    useRegistry: true
    image: "manushau/email-service"
    tag: "latest"
    containerPort: 80
    serviceType: ClusterIP
    servicePort: 80
    healthCheckEnabled: false

  postgres:
    enabled: true
    useRegistry: false
    image: "postgres"
    tag: "15-alpine"
    containerPort: 5432
    serviceType: ClusterIP
    servicePort: 5432
    healthCheckEnabled: false
    env:
      POSTGRES_USER: "adminuser"

  rabbitmq:
    enabled: true
    useRegistry: false
    image: "rabbitmq"
    tag: "3-management"
    containerPort: 5672
    serviceType: ClusterIP
    servicePort: 5672
    healthCheckEnabled: false
