{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ if eq .Release.Namespace "staging" }}staging.{{ else }}prod.{{ end }}{{ .Values.global.domain }}
    http:
      paths:
      # API Gateway Routes (prefixed with /api)
      - path: /api/(auth|products|cart|checkout|orders|admin|health|gateway)(/.*|$)
        pathType: Prefix
        backend:
          service:
            name: api-gateway
            port:
              number: {{ (index .Values.services "api-gateway").servicePort }}
      # Frontend (Catch-all)
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: {{ .Values.services.frontend.servicePort }}
{{- end }}
