{{- range $name, $service := .Values.services }}
{{- if $service.enabled }}
{{- if $service.serviceType }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $name }}
spec:
  type: {{ $service.serviceType }}
  ports:
  - port: {{ $service.servicePort }}
    targetPort: {{ default $service.servicePort $service.containerPort }}
  selector:
    app: {{ $name }}
{{- end }}
{{- end }}
{{- end }}
